version: '3.4'

services:
  trafficcontrolservice:
    image: ${DOCKER_REGISTRY-}trafficcontrolservice
    build:
      context: ./TrafficControlService
      dockerfile: dockerfile

  vehicleregistrationservice:
    image: ${DOCKER_REGISTRY-}vehicleregistrationservice
    build:
      context: ./VehicleRegistrationService
      dockerfile: Dockerfile


  finecollectionservice:
    image: ${DOCKER_REGISTRY-}finecollectionservice
    build:
      context: ./FineCollectionService
      dockerfile: Dockerfile


  simulation:
    image: ${DOCKER_REGISTRY-}simulation
    build:
      context: ./Simulation
      dockerfile: dockerfile

