apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: dapr-trafficcontrol
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: pubsub.sbConnectionString
      key: pubsub.sbConnectionString
auth:
  secretStore: trafficcontrol-secrets
scopes:
  - trafficcontrolservice
  - finecollectionservice